### ISSUE TITLE
September 19th Commitments

### ISSUE THREAD

**Issue by mnatenz1** [NeuroDataDesign/orange-panda#12]
ALL FILES SHOULD BE COMBINED IN ONE NOTEBOOK/RMD

@nkumarcc 
- [x] Fix EEG Fourier Plot - [embedded screenshots and explanations of issues with previous week](http://neurodatadesign.github.io/orange-panda/FourierTransform.html)
- [x] Fix eyetracking sample plots
   - [x] Go over current plots, see if there's a hole in the code or an error in data - paragraph of error
   - [x] See if sudden discontinuities were artifacts or errors - Update questions for Nicolas
   - [ ] Add for the other paradigms - embedded shots and code in notebook
- [x] Read Mike's Note on Neural Analysis Book - [.md of understanding Fourier and other directly relevant stuff](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/eeg_analy_notes/rel_topics.md)

@mnatenz1
- [x] Read 30 pages in book. [Notes here](http://upward-spiral-science.github.io/orange-panda/AnalyzingNeuralTimeSeriesData_Week03.pdf)
- [x] Work on verbal descriptions of pre-processing and analysis for EEG/EyeTracking. [Put into lucid presentation](http://neurodatadesign.github.io/orange-panda/EEGPipeLine.png).

@rmarren1 
- [x] Read Mike's Note on Neural Analysis Book - [.md](https://github.com/NeuroDataDesign/orange-panda/blob/master/brainstorm/time_series_notes_marren.md) of understanding Fourier and other directly relevant stuff
- [x] compile list of preprocessing and analysis functions needed in the pipeline - [google doc of list](https://docs.google.com/document/d/1mR3pLZWoKc5MLTeyEKzi6QSS2G-OZK_2Xd_lkQagSfA/edit?usp=sharing)
- [x] Write pseudocode for preprocessing and analysis (EEG/EyeTracking) in latex - [add code to lucidchart](https://www.lucidchart.com/documents/view/b7187cad-5ebb-4280-9228-732c3267b8bc) ([just the algos in overleaf](https://www.overleaf.com/read/qhfwbrjqvvny))

@tsunwong123 
- [x] Fix heatmaps(ie. remove time = 0) - [screen shot](https://github.com/NeuroDataDesign/orange-panda/blob/master/eeg_data/EEG_Plots/FixedHeatMap.jpeg), [code, and explanation of fix](https://github.com/NeuroDataDesign/orange-panda/blob/master/eeg_data/EEG_Plots/9_19/heatmaplistoffunctions.r)
- [x] Read Mike's Note on Neural Analysis Book - [.md](https://github.com/Upward-Spiral-Science/orange-panda/blob/master/eeg_data/eeg_analy_notes/Tsun_relevant_notes.md) of understanding Fourier and other directly relevant stuff
- [x] Work on verbal descriptions of pre-processing and analysis for EEG/EyeTracking. [Put into lucid presentation](http://neurodatadesign.github.io/orange-panda/EEGPipeLine.png).

**Comment by jovo** [comment]
@rmarren1 get a good example from here: https://www.overleaf.com/5045839tctygn#/19177344/
(scroll to bottom, there are 5 examples).
show 1 example to @gkiar to make sure you understand the format before making all the others.

**Comment by gkiar** [comment]
👌
