### ISSUE TITLE
For September 26th

### ISSUE THREAD

**Issue by tsunwong123** [NeuroDataDesign/orange-panda#13]
- [x] To further understand the preprocessing pipeline. [Ryan's Links for the paper including algorithms here]. Research and take notes on the pros and cons of each method and also how to quantify the success of the algorithm:
   @nkumarcc  - [X] Detecting bad channels - [slides](http://neurodatadesign.github.io/orange-panda/reveal/slides-dete.html)
   @rmarren1 - [X] Interpolating bad channels [.pdf](https://github.com/NeuroDataDesign/orange-panda/blob/62068fe403a58ba4e0eea7c66222b79335ccad92/brainstorm/eeg-pipeline-preprocessing.pdf)
   @mnatenz1 - [X] Removing eye artifacts . .....^^
   @tsunwong123 - [X] Robust PCA [.md](https://github.com/NeuroDataDesign/orange-panda/blob/master/brainstorm/RobustPCA.md)

- [x] Find packages in Python/R for some of the preprocessing algorithms. pyEEG in Python, 'eegAnalysis' in CRAN. Both have basic methods for analysis.

@nkumarcc 
- [X] Fix Fourier Transform graphs [.Rmd](http://neurodatadesign.github.io/orange-panda/FourierTransform.html)
- [ ] Collect details on holes in Eye-Tracking data .md

@rmarren1 
- [x] Demos of basic filtering used on the pipeline [.ipynb](https://github.com/NeuroDataDesign/orange-panda/blob/master/tutorials/Basic%20Filtering.ipynb)

@tsunwong123
- [x] Fix Heatmaps and put time on x-axis. [screenshot](https://github.com/NeuroDataDesign/orange-panda/blob/master/eeg_data/EEG_Plots/HeatmapFixed2.jpeg)
- [x] Research more on filtering. Summarize (Gaussian filters, FIR, IIR, optimize signal-to-noise ratio) [.md] (https://github.com/NeuroDataDesign/orange-panda/blob/master/eeg_data/eeg_analy_notes/Filtering.md)

@mnatenz1 
- [x] Read 60 pages of book. [Notes .doc](http://neurodatadesign.github.io/orange-panda/AnalyzingNeuralTimeSeriesData.pdf)

**Comment by gkiar** [comment]
@tsunwong123 your task should require changing only 1 line of code, what else are you going to do? 👌 for the rest

**Comment by tsunwong123** [comment]
@gkiar Added myself to do some additional readings on some filtering because I think it might be useful. Any specific suggestions on books or anything specific?

**Comment by gkiar** [comment]
Nothing that I've used recently stands out regarding filtering, but any DSP (digital signal processing) book ought to have a good section on filters. 👌
