### ISSUE TITLE
Nov 7th.

### ISSUE THREAD

**Issue by rmarren1** [NeuroDataDesign/orange-panda#20]
@rmarren1:
- [x] - in the webservice, include pre-processing steps and a (separate) pre-processing/quality control report
- [x] - work with @nkumarcc to integrade KDE bad electrode detection into webservice
- [x] - various small changes before demo
  - [x] -separate eeg-related functionality from the 'analysis' rest call, so that later it will be easier to separate timeseries stuff from eeg stuff.
  - [x] - various chart edits for post-processing in jovos coment in #18
  - [x] -make analysis links persist (set up a database, or just search the 'results' folder and auto-populate the 'view' table on user load)
  - [x] - refactor code to make it easier to add things
- [x] - randomized PCA [code.md](https://github.com/NeuroDataDesign/orange-panda/blob/master/pipeline/demos/Randomized%20Eigendecomposition%20with%20Power%20Iteration.ipynb) (or really anything that doesn't explicitly factorize the matrix. i think finding the top k eigenvectors with the power iteration method, where k is how ever many eigenvectors we need for the cumulative variance explained to be nearly 1, which was around k=10 for the EEG data)

@nkumarcc 
- [x] - integrate KDE bad electrode detection into webservice - DoD is working output of bad electrode data in demo
    - [X] - better understand cross validation (which is being used for bandwidth selection in KDE). Need to see if cross validation takes too much time on real data - [.md describing cross validation](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/bad_chan_detect/crossvalid.md) and [description of times taken on real data](https://github.com/NeuroDataDesign/orange-panda/blob/master/pipeline/demos/Bad%20Electrode%20Detection.ipynb)
- [X] - Finish coherence code.md, with correct quantitative metric to see how well it works - [.ipynb](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/analysis/coherence/Coherence.ipynb)
- [ ] - **Reach:** Look into kurtosis and spectra decision making for bad electrodes - LaTeX of concepts and pseudocode
- [ ] - **Reach:** quantitative metrics for distributions to evaluate KDE better than simply qualitatively- LaTeX + potential implementation in .ipynb

@tsunwong123 

- [x] - Pseudo-code for Robust PCA due 11/02, determine what to do from there. Some necessary information [.md](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/noise_reduction/FigureOutRPCA.md) and [LaTeX](https://www.overleaf.com/6854142skxwmyxfjwms#/23377679/)
- [x] - [code.md for Robust PCA](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/noise_reduction/RobustPCA.ipynb)
- [ ] - **Reach:** Implement the Robust PCA Algorithm as part of the pipeline.

@mnatenz1 

- [x] [ICA working](https://htmlpreview.github.io/?https://github.com/NeuroDataDesign/orange-panda/blob/gh-pages/Natenzon_ICA_Codemd.html), with a way to visually analyze the independent components, and select which to remove from the original signal

**Comment by tsunwong123** [comment]
@gkiar

**Comment by gkiar** [comment]
👌

**Comment by jovo** [comment]
- [ ] ICA can subsample
- [ ] do we have design specs for how long things should take?
- [ ] why isn't coherence a matrix?
- [ ] so, do we understand robust pca? let's incorporate?
- [ ] instructions for formatting token?
- [ ] sparklines can be closer vertically to one another
