### ISSUE TITLE
pointers for bad electrode detection

### ISSUE THREAD

**Issue by awakenting** [NeuroDataDesign/orange-panda#30]
Hey,
I saw on the neurodata.io website that you're working on bad electrode detection. I happen to work on the same problem atm so I thought you might be interested into the literature I found:
1. http://journal.frontiersin.org/article/10.3389/fninf.2015.00016/full - they are using 4 criterions for bad channels: strong deviations, correlations, high noise and predictability, their github page: https://github.com/VisLab/EEG-Clean-Tools

2. http://journal.frontiersin.org/article/10.3389/fnhum.2016.00050/full - this is specifically for ERP data 

3. http://ieeexplore.ieee.org/document/6945365/ - they assume that you have a "clean" training session and based on that calculate online whether the channels deviate from that "normal" value. their measure is also based on correlations with neighbouring electrodes

I'm currently working on implementing the first one into this toolbox (https://github.com/bbci/wyrm) but not done yet and also didn't push anything yet.

The mne-python toolbox could also be interesting for you: https://github.com/mne-tools/mne-python/tree/master/mne. Their bad channel detection is only based on zscoring though: https://github.com/mne-tools/mne-python/blob/master/mne/preprocessing/bads.py

Well I hope this is helpful and good luck with the project.

Best,
awakenting

**Comment by rmarren1** [comment]
wow thanks, this is great, i've had a look at the first one but the rest is new and should help a lot in the future!

**Comment by rmarren1** [comment]
@nkumarcc @tsunwong123 @mnatenz1 @jovo ^ Some cool ideas for the future

**Comment by awakenting** [comment]
just found this nice review, overviewing "all" the artifact related methods that exist:
"Methods for artifact detection and removal from scalp EEG: A review"
http://www.sciencedirect.com/science/article/pii/S098770531630199X

I don't want to spam your issues so this shall be the last reference I'll post to this issue. I think I will start collecting them on a wiki page or maybe a separate repo on github but feel free to join/watch/star/fork/contribute if you want :)

**Comment by rmarren1** [comment]
awesome. i've compiled this and some links we had from before into a master list here
https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/Literature_References.md

feel free to pull request or let us know if you make your own list!
