### ISSUE TITLE
For Nov. 28

### ISSUE THREAD

**Issue by rmarren1** [NeuroDataDesign/orange-panda#31]
# Commit
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| 🐼 :  | [New solution for Robust PCA](https://github.com/NeuroDataDesign/orange-panda/issues/24)   | [demo of the format of the code](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/noise_reduction/IntegrationOfRPCAIntoPipeline_11_28_16_01.ipynb) results in prep report @tsunwong123 |
| :panda_face:  |  [MARA algorithm (Complete Algorithm and Simulation described in Algorithm.md)](https://htmlpreview.github.io/?https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/eye_artifact_filter/11_28_2016_Mara_Algorithm.html) |  @mnantez1 |
| :panda_face:  | [Fix the 'broken pipe' issue for webservice](https://github.com/NeuroDataDesign/orange-panda/issues/34) | an explaination the bug and how it was fixed @rmarren1 | 
| :panda_face:   | [dockerize webservice (and put on cortex)](https://github.com/NeuroDataDesign/orange-panda/issues/29) | next demo will be on cortex @rmarren1 |
| :panda_face: | [integrate kurtosis/power spectrum bad electrode detect](https://github.com/NeuroDataDesign/orange-panda/issues/32) | demo of results, [working Kurtosis code.md](https://cdn.rawgit.com/NeuroDataDesign/orange-panda/master/notes/bad_chan_detect/Kurtosis.html) [notebook link](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/bad_chan_detect/Kurtosis.ipynb) and [updated bad electrode detection](https://cdn.rawgit.com/NeuroDataDesign/orange-panda/master/notes/bad_chan_detect/Bad%2BElectrode%2BDetection2.html), meanwhile the [notebook located here](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/demos/Bad%20Electrode%20Detection.ipynb) to show it works @nkumarcc @rmarren1|
| :panda_face:  | [let user choose pipeline steps to use](https://github.com/NeuroDataDesign/orange-panda/issues/33) | demo going through it like user @rmarren1 |
# Reach
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| :panda_face:   | [split git workflow into production and development](https://github.com/NeuroDataDesign/orange-panda/issues/28) | show branches
| :x: | [document dockerhub and functions](https://github.com/NeuroDataDesign/orange-panda/issues/36) | show docs @everyone |
| ❌| [start integrating prep pipeline and investigate other sources](https://github.com/NeuroDataDesign/orange-panda/issues/37) | [beginning notebook](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/bad_chan_detect/The%20PREP%20Pipeline%20interpreted.ipynb) @nkumarcc |

**Comment by rmarren1** [comment]
@mnatenz1 @nkumarcc @tsunwong123 anything else?

**Comment by jovo** [comment]
@nkumarcc 
- [ ] if your notebook is better than algorithm.md in certain ways, please tell me how so we can jointly improve
- [ ] do you know the formal definition of kurtosis/skewness?
- [ ] does your webpage have a description pipeline schematic illustration which steps you are performing?
- [ ] current pseudocode for "bad electrode detection"?
- [ ] what is the prep pipeline?
- [ ]

**Comment by ebridge2** [comment]
@mnatenz1 "Uses a machine learning algorithm..." which? Is it arbitrary?
