### ISSUE TITLE
December 5th

### ISSUE THREAD

**Issue by rmarren1** [NeuroDataDesign/orange-panda#42]
# Commit
### http://cortex.jhu.edu:8011
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| 🐼 :  | [Scale Robust PCA for webservice](https://github.com/NeuroDataDesign/orange-panda/issues/24) and [Algorithms.md for Removing Outliers](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/noise_reduction/Removing%2BOutliers.ipynb)   | [demo of the format of the code](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/noise_reduction/IntegrationOfRPCAIntoPipeline_11_28_16_01.ipynb) results in prep report @tsunwong123 |
| :panda_face:  |  [Flow Chart](https://github.com/NeuroDataDesign/orange-panda/issues/41) | available in the about tab on web service (http://cortex.jhu.edu:8011) @rmarren1|
| 🐼 :  | [Choose which pipeline processes to use from EEGLAB set](https://github.com/NeuroDataDesign/orange-panda/issues/39) | [python notebook with simulations](https://cdn.rawgit.com/NeuroDataDesign/orange-panda/master/notes/bad_chan_detect/Algorithm%2BComparison%2B2.html) @nkumarcc | 
| :panda_face:  | Algorithm, Simulation, and Analysis for KS Artifact Rejection Method ([Algorithm.md](https://htmlpreview.github.io/?https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/eye_artifact_filter/Natenzon_KSTest_Algorithm.html))| @mnatenz1 |
| :panda_face:  | [Simplify steps for demo (user doesn't choose, we choose)](https://github.com/NeuroDataDesign/orange-panda/issues/43) |  [details of changes](https://github.com/NeuroDataDesign/orange-panda/issues/43) @rmarren1|
| :panda_face:  | [Document EVERYTHING](https://github.com/NeuroDataDesign/orange-panda/issues/36)  | details of docs created [here](https://github.com/NeuroDataDesign/orange-panda/issues/36) @rmarren1 |

# Reach
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| ⏳ :  | [Use discriminability to decide best threshold for bad electrode detection](https://github.com/NeuroDataDesign/orange-panda/issues/40) | [python notebook with simulations](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/bad_chan_detect/Threshold%20Decision.ipynb) @nkumarcc |

**Comment by jovo** [comment]
- [ ] documentation should all go in webpage, possibly in "about", at least linked to from webpage, so there is a coherent place to get everything
- [ ] how was algorithms.md?
- [ ] what is our current recommendation for bad electrode detection?
- [ ] did KS test "work"?
- [ ] median of what?

**Comment by ebridge2** [comment]
@nkumarcc, discussed in class, but when using multi part algorithms (ie, discriminability is a distance step, a rdf step, and then a discr step) make your stuff fit the first step, and leave the rest the same. Ie, only touch the distance step and make that work for you; dont toucg working implementations of rdf and discriminability. Gives you less to rewrite, and concentrates down the number of sources of errors if you make a mistake adjusting code.
