### ISSUE TITLE
February 5th deliverables

### ISSUE THREAD

**Issue by rmarren1** [NeuroDataDesign/orange-panda#50]
# Commit
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| :panda_face: | Optimize python abstract discriminibility function (O(n^2) rather than O(n^3)), ~pip~ easy installable | [.ipybn](http://pythonhosted.org/py_disc/) [pip page](https://pypi.python.org/pypi/py_disc/1) @rmarren1 |
|  :panda_face: | Interpolation benchmarking using correlation  | [.ipybn](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/interpolation/Benchmarking%20Interpolation.ipynb) @rmarren1 |
|  🐼 :    | Benchmark Robust PCA methods |  [.ipybn](http://nbviewer.jupyter.org/github/neurodatadesign/orange-panda/blob/master/notes/noise_reduction/Benchmarking_RPCA.ipynb) @tsunwong123  |
| :panda_face: | MEDA for electrodes (with notes on how to determine what is 'bad')| [.csv](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/exploratory_analysis/exploratory.csv), [HTMLViewer](https://rawgit.com/), [dir of HTML](https://github.com/NeuroDataDesign/orange-panda/tree/master/notes/exploratory_analysis)   @nkumarcc |

**Comment by rmarren1** [comment]
@jovo

**Comment by ebridge2** [comment]
@rmarren1 if citing discriminability for functions, should use names that the paper uses. ie, rdf (reliability density function) not partial discriminability.

**Comment by ebridge2** [comment]
look at using kullback leibler divergence. basically, fft per electrode, convert to amplitude/power/etc spectrum in Fourier domain, KLD btwn each electrode's spectrum (gives nxn matrix for n electrodes per sub), then directly use distance or something btwn matrices then discriminability computation
