### ISSUE TITLE
Mar. 6

### ISSUE THREAD

**Issue by rmarren1** [NeuroDataDesign/orange-panda#54]
# Monday Commitments
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| :panda_face:   | Methods.md for other denoising techniques (other than PCA or RPCA which did not give good results)    | [file](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/noise_reduction/Wavelet%20Based%20Denoising%20using%20SureShrink.ipynb)@rmarren1 |
| 🐼 | Code to organize eye-tracking data into blinks, saccades, and fixations. Then organize the eye-tracking data with the EEG data according to trials and triggers. | @tsunwong123 [EEGMethods.md](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/analysis/EEGTrials_Methods.md%20%281%29.ipynb) [EEGActualData](http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/5pp91fmidltc2e1/EEGTrialAlignment%20%286%29.ipynb) [Eyetrack.ipynb](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/analysis/EyeTrackingPlots%20%281%29.ipynb) [Code to Integrate into Pipeline](http://nbviewer.jupyter.org/urls/dl.dropbox.com/s/ixee9lutko69lk5/Combination.ipynb) |
| 🐼 | Finish comparison graphs  | [.ipynb with plots](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/exploratory_analysis/BadElectrodeAnalysis.ipynb) @nkumarcc |
| 🐼  | observe plots to figure out different methods that make sense for bad electrode detection and what to show to Nicolas  | [pairs plots](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/exploratory_analysis/JustLookAtIt.ipynb) @nkumarcc |

# Thursday Checkpoint
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| :panda_face: : | Measure discriminibility of the interpolations done by Nicolas, determine whether it helped. If so, attempt to re-create results with our data and interpolation method. | [repo](https://github.com/rmarren1/auto_bench)@rmarren1   |
| :x: | refactor and then document benchmarking tools| @rmarren1 -- walk through of how one of the benchmark notebooks was produced using this utility.|
| :x: | Research some noise reduction papers and discuss with greg which look the most promising | @rmarren1 |
| ⏳  | To show that it is necessary to label the trials of EEG data by showing an unaligned version. | [.ipynb](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/analysis/EEGTrials_Methods.md.ipynb) @tsunwong123
| ⏳  | Make a few eye-tracking data plots | [.ipynb](https://github.com/NeuroDataDesign/orange-panda/blob/master/notes/analysis/EyeTrackingPlots.ipynb) @tsunwong123 |
| ⌛️ | Make plots as specified by [Greg's comment here.](https://github.com/NeuroDataDesign/orange-panda/issues/53) See if there's anything that stands out about the data. | [.ipynb with the actual plots](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/exploratory_analysis/BadElectrodeAnalysis.ipynb) [.ipynb for pairs plot](http://nbviewer.jupyter.org/github/NeuroDataDesign/orange-panda/blob/master/notes/exploratory_analysis/JustLookAtIt.ipynb) @nkumarcc |

**Comment by rmarren1** [comment]
@gkiar @tsunwong123 @nkumarcc

**Comment by gkiar** [comment]
@nkumarcc do you have any issues for the week?
@tsunwong123 the definition of done for your Monday deliverable are plots showing me the raw (un- aligned/processed/whatever) data all side by side, and then the same plots showing me that data after your processing. This should **importantly** only be shown after you prove to me that your code works on simulated data, by doing a `methods.md` for it.
@rmarren1 👌

**Comment by nkumarcc** [comment]
@gkiar: updated

**Comment by gkiar** [comment]
👌
