### ISSUE TITLE
For April 16th

### ISSUE THREAD

**Issue by rmarren1** [NeuroDataDesign/orange-panda#60]
# Monday Commitments
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| :panda_face:   | Docker Image which will run our pipeline on one individual, for use in batch. Use new better plots. | [dockerhub](https://hub.docker.com/r/rymarr/panda_pipeline/) [github](https://github.com/rmarren1/panda)  results on neurodatadesign-test bucket. @rmarren1 |
| :panda_face: | Test interpolation method to replace SSI, new discriminibility. | [image](https://cloud.githubusercontent.com/assets/10272301/25103856/fd529bcc-238b-11e7-8f4c-0254342d8df7.png) @rmarren1 |
| :-1: : | Full pipeline AWS integrated | @nkumarcc |
| :panda_face: : | Get a "hello world" AWS Batch instance running such that our pipeline can easily be added to it | [dir with files, need to run locally](https://github.com/NeuroDataDesign/orange-panda/tree/master/web) @nkumarcc  |
| :panda_face: : | Updated flow chart | [cloudy flowchart diagram](https://github.com/NeuroDataDesign/orange-panda/blob/master/panda_cloud.jpeg) @nkumarcc  |

# Thursday Commitments
| Status |     Task         | Deliverable      |
|:-------:|---------------|------------------|
| :x:  | Find hypterparameter for SSI which returns reasonable results. |  @rmarren1  |
| :x: | Come with loaded data from each pipeline step. Hack with greg to find the most meaningful visualizations | @rmarren1  |

**Comment by rmarren1** [comment]
@nkumarcc @gkiar

**Comment by jovo** [comment]
@rmarren1 it seems that only eog_regress is useful.  what is discriminability missing?
